### ISSUE TITLE
Add support for low-level interface in JSON schema

### ISSUE THREAD

**Issue by Selfeer** [Altinity/parquet-regression#5]
https://github.com/apache/parquet-java/blob/master/parquet-column/src/test/java/org/apache/parquet/column/impl/TestColumnReaderImpl.java#L55

**Comment by Selfeer** [comment]
The current implementation for generating Parquet files utilizes the [ExampleParquetWriter](https://github.com/Altinity/parquet-regression/blob/c34fa831e0f8f093bfe402c0b81052e81dfe3d12/parquetify/src/main/java/GenerateParquet.java#L118C9-L118C29), which is a high-level implementation that offers many options but does not allow fine-tuning of everything.

[parquet-java](https://github.com/apache/parquet-java/tree/master) seems to be using a more low-level implementation in their tests, shown here: https://github.com/apache/parquet-java/blob/master/parquet-column/src/test/java/org/apache/parquet/column/impl/TestColumnReaderImpl.java#L55

We need to check if it's possible to use this low-level approach when generating Parquet files and implement it without removing the current implementation.

**Comment by strtgbb** [comment]
1. The functions called in that test are not public, we cannot use them
2. The test appears to be using them to test read and write in-memory, without ever writing to disk
3. The config options in that test are already accessible in our current code
4. We could create our own extension of ParquetWriter to replace ExampleParquetWriter

Can you elaborate on what fine-tuning you'd like to access?

**Comment by Selfeer** [comment]
It seems like we don't actually need any lower level implementation, closing the issue.
